// <auto-generated />
using System;
using CryptoIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoIntelligenceDbContext))]
    [Migration("20260727211030_004_NewTokenRadarProjections")]
    partial class _004_NewTokenRadarProjections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.ConfigurationSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_json");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("configuration_hash")
                        .IsFixedLength();

                    b.Property<string>("ConfigurationVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_snapshots_hash");

                    b.HasIndex("ConfigurationVersion", "CreatedAtUtc")
                        .HasDatabaseName("ix_configuration_snapshots_version_created");

                    b.ToTable("configuration_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.FeatureSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AsOfSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("as_of_slot");

                    b.Property<DateTimeOffset>("AsOfTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_time");

                    b.Property<DateTimeOffset>("ComputedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_time");

                    b.Property<string>("EntityNaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_natural_key");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FeatureSetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_set_version");

                    b.Property<int>("SourceEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_event_count");

                    b.Property<long>("SourceFromSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("source_from_slot");

                    b.Property<long>("SourceToSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("source_to_slot");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityNaturalKey", "FeatureSetVersion", "AsOfSlot")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_snapshots_entity_version_slot");

                    b.ToTable("feature_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<long>("FinalizedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("finalized_through_slot");

                    b.Property<string>("LastCompletedSignature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_completed_signature");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<long>("ObservedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_through_slot");

                    b.Property<long>("PersistedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("persisted_through_slot");

                    b.Property<long>("ProcessedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_through_slot");

                    b.Property<long>("ReconciledThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("reconciled_through_slot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subscription_type");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "Network", "Source", "SubscriptionType")
                        .IsUnique()
                        .HasDatabaseName("ux_ingestion_checkpoints_source_subscription");

                    b.ToTable("ingestion_checkpoints", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionSlotStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<bool>("Finalized")
                        .HasColumnType("boolean")
                        .HasColumnName("finalized");

                    b.Property<string>("GapReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("gap_reason");

                    b.Property<bool>("HasGap")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gap");

                    b.Property<bool>("Observed")
                        .HasColumnType("boolean")
                        .HasColumnName("observed");

                    b.Property<bool>("Persisted")
                        .HasColumnType("boolean")
                        .HasColumnName("persisted");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("boolean")
                        .HasColumnName("reconciled");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ux_ingestion_slot_states_checkpoint_slot");

                    b.ToTable("ingestion_slot_states", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_amount");

                    b.Property<decimal>("BaseReserveAfter")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_reserve_after");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<int>("LiquidityIndex")
                        .HasColumnType("integer")
                        .HasColumnName("liquidity_index");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<decimal>("QuoteAmount")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_amount");

                    b.Property<decimal>("QuoteReserveAfter")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_reserve_after");

                    b.Property<Guid>("RawEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_event_id");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("RawEventId", "PoolId", "LiquidityIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_liquidity_events_raw_pool_index");

                    b.ToTable("liquidity_events", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityPoolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseReserve")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_reserve");

                    b.Property<Guid>("BaseTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_token_id");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<long>("CreatedSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("created_slot");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Dex")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dex");

                    b.Property<DateTimeOffset>("FirstObservedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_time");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<string>("PoolAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pool_address");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("program_id");

                    b.Property<decimal>("QuoteReserve")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_reserve");

                    b.Property<Guid>("QuoteTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_token_id");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("BaseTokenId");

                    b.HasIndex("QuoteTokenId");

                    b.HasIndex("Chain", "Network", "PoolAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_pools_chain_network_address");

                    b.ToTable("liquidity_pools", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.MarketSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AsOfSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("as_of_slot");

                    b.Property<DateTimeOffset>("AsOfTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_time");

                    b.Property<decimal>("BaseReserve")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_reserve");

                    b.Property<decimal>("BaseVolume")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_volume");

                    b.Property<int>("BuyCount")
                        .HasColumnType("integer")
                        .HasColumnName("buy_count");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("EventIndex")
                        .HasColumnType("integer")
                        .HasColumnName("event_index");

                    b.Property<decimal>("LiquidityInQuote")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("liquidity_in_quote");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("PriceImpactBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("price_impact_basis_points");

                    b.Property<decimal>("PriceInQuote")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price_in_quote");

                    b.Property<decimal>("QuoteReserve")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_reserve");

                    b.Property<Guid>("QuoteTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_token_id");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_volume");

                    b.Property<int>("SellCount")
                        .HasColumnType("integer")
                        .HasColumnName("sell_count");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("TraderAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trader_address");

                    b.HasKey("Id");

                    b.HasIndex("PoolId", "AsOfTime")
                        .HasDatabaseName("ix_market_snapshots_pool_time");

                    b.HasIndex("PoolId", "AsOfSlot", "EventIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_market_snapshots_pool_slot_index");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.NormalizedDomainEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("DomainEventIndex")
                        .HasColumnType("integer")
                        .HasColumnName("domain_event_index");

                    b.Property<string>("DomainEventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain_event_type");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parser_version");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("program_id");

                    b.Property<Guid>("RawEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_event_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "EventTime")
                        .HasDatabaseName("ix_normalized_events_program_time");

                    b.HasIndex("RawEventId", "DomainEventType", "DomainEventIndex", "ParserVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_normalized_events_parser_identity");

                    b.ToTable("normalized_domain_events", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.RawBlockchainEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("block_hash");

                    b.Property<string>("CanonicalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("canonical_status");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<string>("CommitmentLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("commitment_level");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("event_id")
                        .IsFixedLength();

                    b.Property<int>("EventOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("event_ordinal");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("FinalityUpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finality_updated_time");

                    b.Property<DateTimeOffset?>("FinalizedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_time");

                    b.Property<DateTimeOffset?>("FirstFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failure_time");

                    b.Property<int?>("InnerInstructionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("inner_instruction_index");

                    b.Property<int>("InstructionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("instruction_index");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_time");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<DateTimeOffset>("ObservedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_time");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("program_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("RevertReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("revert_reason");

                    b.Property<DateTimeOffset?>("RevertedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reverted_time");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("TransactionSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("transaction_signature");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_events_event_id");

                    b.HasIndex("TransactionSignature")
                        .HasDatabaseName("ix_raw_events_signature");

                    b.HasIndex("EventType", "EventTime")
                        .HasDatabaseName("ix_raw_events_type_time");

                    b.HasIndex("Network", "Slot")
                        .HasDatabaseName("ix_raw_events_network_slot");

                    b.HasIndex("ProcessingStatus", "ObservedTime")
                        .HasDatabaseName("ix_raw_events_processing_time");

                    b.HasIndex("ProgramId", "EventTime")
                        .HasDatabaseName("ix_raw_events_program_time");

                    b.HasIndex("Chain", "Network", "TransactionSignature", "InstructionIndex", "InnerInstructionIndex", "EventType", "EventOrdinal", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_events_chain_identity");

                    b.ToTable("raw_blockchain_events", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.SwapEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("base_amount");

                    b.Property<Guid>("BaseTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_token_id");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<DateTimeOffset>("ObservedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_time");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("PriceImpactBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("price_impact_basis_points");

                    b.Property<decimal>("PriceInQuote")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price_in_quote");

                    b.Property<decimal>("QuoteAmount")
                        .HasPrecision(38)
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("quote_amount");

                    b.Property<Guid>("QuoteTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_token_id");

                    b.Property<Guid>("RawEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_event_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.Property<int>("SwapIndex")
                        .HasColumnType("integer")
                        .HasColumnName("swap_index");

                    b.Property<Guid?>("TraderWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("BaseTokenId");

                    b.HasIndex("QuoteTokenId");

                    b.HasIndex("TraderWalletId");

                    b.HasIndex("PoolId", "EventTime")
                        .HasDatabaseName("ix_swaps_pool_time");

                    b.HasIndex("RawEventId", "PoolId", "SwapIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_swaps_raw_pool_index");

                    b.ToTable("swap_events", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenCandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_token_candidates_token");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_token_candidates_status_updated");

                    b.ToTable("token_candidates", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<long>("CreatedSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("created_slot");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTimeOffset>("FirstObservedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_time");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("MintAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mint_address");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "Network", "MintAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_tokens_chain_network_mint");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.WalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<long>("FirstSeenSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("first_seen_slot");

                    b.Property<DateTimeOffset>("FirstSeenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_time");

                    b.Property<DateTimeOffset>("LastSeenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_time");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "Network", "Address")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_chain_network_address");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionSlotStateEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionCheckpointEntity", null)
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityEventEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityPoolEntity", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.RawBlockchainEventEntity", null)
                        .WithMany()
                        .HasForeignKey("RawEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityPoolEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("BaseTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("QuoteTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.NormalizedDomainEventEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.RawBlockchainEventEntity", null)
                        .WithMany()
                        .HasForeignKey("RawEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.SwapEventEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("BaseTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.LiquidityPoolEntity", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("QuoteTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.RawBlockchainEventEntity", null)
                        .WithMany()
                        .HasForeignKey("RawEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.WalletEntity", null)
                        .WithMany()
                        .HasForeignKey("TraderWalletId");
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenCandidateEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
