// <auto-generated />
using System;
using CryptoIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoIntelligenceDbContext))]
    [Migration("20260727201001_002_ReliableIngestionFoundation")]
    partial class _002_ReliableIngestionFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.ConfigurationSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_json");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("configuration_hash")
                        .IsFixedLength();

                    b.Property<string>("ConfigurationVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_snapshots_hash");

                    b.HasIndex("ConfigurationVersion", "CreatedAtUtc")
                        .HasDatabaseName("ix_configuration_snapshots_version_created");

                    b.ToTable("configuration_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<long>("FinalizedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("finalized_through_slot");

                    b.Property<string>("LastCompletedSignature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_completed_signature");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<long>("ObservedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_through_slot");

                    b.Property<long>("PersistedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("persisted_through_slot");

                    b.Property<long>("ProcessedThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_through_slot");

                    b.Property<long>("ReconciledThroughSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("reconciled_through_slot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subscription_type");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "Network", "Source", "SubscriptionType")
                        .IsUnique()
                        .HasDatabaseName("ux_ingestion_checkpoints_source_subscription");

                    b.ToTable("ingestion_checkpoints", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionSlotStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<bool>("Finalized")
                        .HasColumnType("boolean")
                        .HasColumnName("finalized");

                    b.Property<string>("GapReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("gap_reason");

                    b.Property<bool>("HasGap")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gap");

                    b.Property<bool>("Observed")
                        .HasColumnType("boolean")
                        .HasColumnName("observed");

                    b.Property<bool>("Persisted")
                        .HasColumnType("boolean")
                        .HasColumnName("persisted");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("boolean")
                        .HasColumnName("reconciled");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ux_ingestion_slot_states_checkpoint_slot");

                    b.ToTable("ingestion_slot_states", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.RawBlockchainEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("block_hash");

                    b.Property<string>("CanonicalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("canonical_status");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<string>("CommitmentLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("commitment_level");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("event_id")
                        .IsFixedLength();

                    b.Property<int>("EventOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("event_ordinal");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("FinalityUpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finality_updated_time");

                    b.Property<DateTimeOffset?>("FinalizedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_time");

                    b.Property<DateTimeOffset?>("FirstFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failure_time");

                    b.Property<int?>("InnerInstructionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("inner_instruction_index");

                    b.Property<int>("InstructionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("instruction_index");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_time");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<DateTimeOffset>("ObservedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_time");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("program_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("RevertReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("revert_reason");

                    b.Property<DateTimeOffset?>("RevertedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reverted_time");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.Property<long>("Slot")
                        .HasColumnType("bigint")
                        .HasColumnName("slot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("TransactionSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("transaction_signature");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_events_event_id");

                    b.HasIndex("TransactionSignature")
                        .HasDatabaseName("ix_raw_events_signature");

                    b.HasIndex("EventType", "EventTime")
                        .HasDatabaseName("ix_raw_events_type_time");

                    b.HasIndex("Network", "Slot")
                        .HasDatabaseName("ix_raw_events_network_slot");

                    b.HasIndex("ProcessingStatus", "ObservedTime")
                        .HasDatabaseName("ix_raw_events_processing_time");

                    b.HasIndex("ProgramId", "EventTime")
                        .HasDatabaseName("ix_raw_events_program_time");

                    b.HasIndex("Chain", "Network", "TransactionSignature", "InstructionIndex", "InnerInstructionIndex", "EventType", "EventOrdinal", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_events_chain_identity");

                    b.ToTable("raw_blockchain_events", (string)null);
                });

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionSlotStateEntity", b =>
                {
                    b.HasOne("CryptoIntelligence.Infrastructure.Persistence.Entities.IngestionCheckpointEntity", null)
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
