// <auto-generated />
using System;
using CryptoIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoIntelligenceDbContext))]
    partial class CryptoIntelligenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoIntelligence.Infrastructure.Persistence.Entities.ConfigurationSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_json");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("configuration_hash")
                        .IsFixedLength();

                    b.Property<string>("ConfigurationVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_snapshots_hash");

                    b.HasIndex("ConfigurationVersion", "CreatedAtUtc")
                        .HasDatabaseName("ix_configuration_snapshots_version_created");

                    b.ToTable("configuration_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
